import { cn } from "@/lib/utils";

type StatusTone = "status-success" | "status-danger" | "status-warning" | "status-info";

const statusLabels: Record<string, { label: string; tone: StatusTone }> = {
  aktif: { label: "Aktif", tone: "status-success" },
  active: { label: "Aktif", tone: "status-success" },
  berhasil: { label: "Berhasil", tone: "status-success" },
  success: { label: "Berhasil", tone: "status-success" },
  selesai: { label: "Selesai", tone: "status-success" },
  complete: { label: "Selesai", tone: "status-success" },
  completed: { label: "Selesai", tone: "status-success" },
  dibayar: { label: "Dibayar", tone: "status-success" },
  paid: { label: "Dibayar", tone: "status-success" },
  diproses: { label: "Diproses", tone: "status-success" },
  processing: { label: "Diproses", tone: "status-success" },
  dikonfirmasi: { label: "Dikonfirmasi", tone: "status-success" },
  confirmed: { label: "Dikonfirmasi", tone: "status-success" },
  diterima: { label: "Diterima", tone: "status-success" },
  approved: { label: "Disetujui", tone: "status-success" },
  disetujui: { label: "Disetujui", tone: "status-success" },
  lunas: { label: "Lunas", tone: "status-success" },
  settled: { label: "Tuntas", tone: "status-success" },
  tuntas: { label: "Tuntas", tone: "status-success" },
  dibaca: { label: "Dibaca", tone: "status-success" },
  read: { label: "Dibaca", tone: "status-success" },
  batal: { label: "Dibatalkan", tone: "status-danger" },
  dibatalkan: { label: "Dibatalkan", tone: "status-danger" },
  cancel: { label: "Dibatalkan", tone: "status-danger" },
  canceled: { label: "Dibatalkan", tone: "status-danger" },
  cancelled: { label: "Dibatalkan", tone: "status-danger" },
  dikembalikan: { label: "Dikembalikan", tone: "status-danger" },
  refund: { label: "Dikembalikan", tone: "status-danger" },
  refunded: { label: "Dikembalikan", tone: "status-danger" },
  ditolak: { label: "Ditolak", tone: "status-danger" },
  refused: { label: "Ditolak", tone: "status-danger" },
  rejected: { label: "Ditolak", tone: "status-danger" },
  kedaluwarsa: { label: "Kedaluwarsa", tone: "status-danger" },
  expired: { label: "Kedaluwarsa", tone: "status-danger" },
  gagal: { label: "Gagal", tone: "status-danger" },
  failed: { label: "Gagal", tone: "status-danger" },
  nonaktif: { label: "Nonaktif", tone: "status-danger" },
  inactive: { label: "Nonaktif", tone: "status-danger" },
  menunggu: { label: "Menunggu", tone: "status-warning" },
  pending: { label: "Menunggu", tone: "status-warning" },
  waiting: { label: "Menunggu", tone: "status-warning" },
  menunggu_pembayaran: { label: "Menunggu pembayaran", tone: "status-warning" },
  pending_payment: { label: "Menunggu pembayaran", tone: "status-warning" },
  menunggu_verifikasi: { label: "Menunggu verifikasi", tone: "status-warning" },
  pending_verification: { label: "Menunggu verifikasi", tone: "status-warning" },
  rendah: { label: "Rendah", tone: "status-warning" },
  low: { label: "Rendah", tone: "status-warning" },
  stok_menipis: { label: "Stok menipis", tone: "status-warning" },
  low_stock: { label: "Stok menipis", tone: "status-warning" },
  stok_habis: { label: "Stok habis", tone: "status-danger" },
  out_of_stock: { label: "Stok habis", tone: "status-danger" },
  daftar_tunggu: { label: "Daftar tunggu", tone: "status-warning" },
  waitlist: { label: "Daftar tunggu", tone: "status-warning" },
  baru: { label: "Baru", tone: "status-warning" },
  new: { label: "Baru", tone: "status-warning" },
  belum: { label: "Belum", tone: "status-warning" },
  belum_dibaca: { label: "Belum dibaca", tone: "status-warning" },
  unread: { label: "Belum dibaca", tone: "status-warning" },
  belum_terverifikasi: { label: "Belum terverifikasi", tone: "status-warning" },
  unverified: { label: "Belum terverifikasi", tone: "status-warning" },
  belum_dikonfirmasi: { label: "Belum dikonfirmasi", tone: "status-warning" },
  unconfirmed: { label: "Belum dikonfirmasi", tone: "status-warning" },
  hampir_penuh: { label: "Hampir penuh", tone: "status-warning" },
  draf: { label: "Draf", tone: "status-info" },
  draft: { label: "Draf", tone: "status-info" },
  ditinjau: { label: "Ditinjau", tone: "status-info" },
  reviewed: { label: "Ditinjau", tone: "status-info" },
  tayang: { label: "Tayang", tone: "status-info" },
  published: { label: "Tayang", tone: "status-info" },
};

function normalizeStatus(status: string) {
  return status.trim().toLocaleLowerCase("id-ID").replace(/[\s-]+/g, "_");
}

export function StatusBadge({ status }: { status: string }) {
  const mapped = statusLabels[normalizeStatus(status)] ?? { label: "Status lainnya", tone: "status-info" as const };
  return <span className={cn("badge badge-dot", mapped.tone)}>{mapped.label}</span>;
}
